steps:
  - label: "🌙 Process FREN PRs"
    command: |
      nix build .#fren-processor
      ./result/bin/fren_processor
      echo "✓ Monster Moonshine encoding complete"
  
  - label: "🔷 Paxos Witness (23 Nodes)"
    command: |
      nix build .#paxos-witness
      ./result/bin/paxos_witness
      echo "✓ Resonant node selected"
      echo "✓ Shared memory witness recorded"
      jq '.' witnesses/node*_shard*.json
  
  - label: "🔬 Verify Quorum"
    command: |
      echo "Checking Byzantine fault tolerance..."
      echo "Quorum: 12/23 nodes required"
      jq '.quorum_vote, .resonance_score' witnesses/*.json
